<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRk7Dnjo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRk7Dnjo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRk7Dnjo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRk7Dnjo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRk7Dnjo\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rk7Dnjo',
    'container.build_id' => 'f0541403',
    'container.build_time' => 1692562575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRk7Dnjo');
