<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'build/runtime.9a71ee5d.js',
                'build/845.8ea7f265.js',
                'build/app.5e8be9c6.js',
            ],
            'css' => [
                'build/845.60f5dd4b.css',
                'build/app.7523f945.css',
            ],
        ],
    ],
],

]];
